"""initial schema: admins, grants, sessions, events

Revision ID: 5114664683c7
Revises: 
Create Date: 2026-10-06 23:37:33.696677

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5114664683c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('totp_secret_enc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.Column('grant_public_id', sa.String(length=16), nullable=True),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_grant_id'), ['grant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_events_ts_type', ['ts', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('vendor_email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('allowed_paths', sa.JSON(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('link_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('bound_device_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grants_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_grants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_grants_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_grants_vendor_email'), ['vendor_email'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_grant_id'), ['grant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_session_hash'), ['session_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_session_hash'))
        batch_op.drop_index(batch_op.f('ix_sessions_grant_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grants_vendor_email'))
        batch_op.drop_index(batch_op.f('ix_grants_token_hash'))
        batch_op.drop_index(batch_op.f('ix_grants_status'))
        batch_op.drop_index(batch_op.f('ix_grants_public_id'))

    op.drop_table('grants')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index('ix_events_ts_type')
        batch_op.drop_index(batch_op.f('ix_events_ts'))
        batch_op.drop_index(batch_op.f('ix_events_grant_id'))

    op.drop_table('events')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
